<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="GAURANGA-PC" name="com.SeleniumLearn.testCases.AddCustomerTest" tests="5" failures="0" timestamp="2021-05-13T10:44:58 IST" time="0.030" errors="1">
  <testcase name="addCustomerTest" time="0.000" classname="com.SeleniumLearn.testCases.AddCustomerTest">
    <skipped/>
  </testcase> <!-- addCustomerTest -->
  <system-out>
    <![CDATA[test case finish]]>
  </system-out>
  <testcase name="addCustomerTest" time="0.000" classname="com.SeleniumLearn.testCases.AddCustomerTest">
    <skipped/>
  </testcase> <!-- addCustomerTest -->
  <system-out>
    <![CDATA[test case start]]>
  </system-out>
  <testcase name="addCustomerTest" time="0.000" classname="com.SeleniumLearn.testCases.AddCustomerTest">
    <skipped/>
  </testcase> <!-- addCustomerTest -->
  <system-out>
    <![CDATA[test case start]]>
  </system-out>
  <testcase name="setUP" time="0.027" classname="com.SeleniumLearn.testCases.AddCustomerTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.SeleniumLearn.base.TestBase.setUP(TestBase.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- setUP -->
  <system-out/>
  <testcase name="addCustomerTest" time="0.003" classname="com.SeleniumLearn.testCases.AddCustomerTest">
    <skipped/>
  </testcase> <!-- addCustomerTest -->
  <system-out>
    <![CDATA[test case start]]>
  </system-out>
</testsuite> <!-- com.SeleniumLearn.testCases.AddCustomerTest -->
